/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author sistemas
 */
public class Panel extends javax.swing.JPanel {
    private int x,y;
    
    /**
     * Creates new form Panel
     * @param g
     */
    /*  public Panel() {
        //this.setSize(100,100);
       
    }
    */
    
    public Panel(int x, int y){
        
        
        this.x = x;
        this.y = y;
    }

    @Override
    public void paint(Graphics g) {
        Image imagen = new ImageIcon(getClass().
                getResource("/pics/Mario.png")).getImage();
        Graphics2D g2 = (Graphics2D) g;
        
        g2.drawImage(imagen, this.x, this.y, 100, 100, this);
        setOpaque(false);
        super.paint(g2);
    }
    public void mover(){
        this.x++;
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
